# Generated by Django 2.1.2 on 2018-11-16 15:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='cost'))
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='DishModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'modifier',
                'verbose_name_plural': 'modifiers',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('details', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'spot',
                'verbose_name_plural': 'spots',
            },
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['name'], name='spot_menu_s_name_37d62e_idx'),
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dish_modifiers', to='spot_menu.Dish'),
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='spot_menu.DishModifier'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(to='spot_menu.Category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='spot_menu.Spot'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='spot_menu_c_name_d66c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['spot', 'name'], name='spot_menu_d_spot_id_e2d3e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('spot', 'name')},
        ),
    ]
